villa_navi_service:
    ref_frame: "map"
    goal:
        x: 0.8
        y: 0.8
        t: 0.0 
    door:
        x: 4.54
        y: 0.375
        t: 0.0
    living_room:
        x: 10.0
        y: -2.0
        t: 0.0
    home_pos:
        x: 0.0
        y: 0.0
        t: 0.0
    corridor:
        x: 5.3
        y: 1.5
        t: 1.5
